<?php

namespace M2I\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
	public function findAllOrderByCreateDate()
	{
		$qb = $this->createQueryBuilder('article');

		$qb->orderBy('article.createDate', 'DESC');

		return $qb->getQuery()->getResult();
	}
}
